### PR TITLE
Add Thermo Stellar MS

### PR DESCRIPTION
**Pull request by edeutsch**

### CODE REVIEW

**Comment by chambm** [comment]
I was wondering whether it should mention that the ion trap is dual pressure, but then I remember the Velos is as well, and it seems the older Thermo CV terms don't include instrument components at all. So what's there is probably fine.

**Review by chambm — APPROVED** [review]

**Comment by jshofstahl** [comment]
Looks good to me.

**Review by mobiusklein — APPROVED** [review]
After fixing the term ID, this looks fine to me.

**Review by vagisha — APPROVED** [review]
Looks good to me.  Thank you.

**Pull request merged**
