### PR TITLE
Switch to PURL for OBO imports

### PR DESCRIPTION
**Pull request by chambm**
@edeutsch is right that the robot convert step is already changing the OBO imports to OWL.

### CODE REVIEW

**Comment by mobiusklein** [comment]
Yes, https://github.com/HUPO-PSI/psi-ms-CV/blob/master/.github/workflows/tag-pr.yml#L29-L45 takes care of that conversion. By changing the URL in the OBO, it will also be reflected in the OWL file.

**Comment by edeutsch** [comment]
great, it looks like it is location independent, so if we change the URL a bit, it should still work fine. thanks!

**Comment by chambm** [comment]
Hmm any idea why it failed @mobiusklein ? https://github.com/HUPO-PSI/psi-ms-CV/runs/4729786428?check_suite_focus=true

**Comment by mobiusklein** [comment]
It seems `robot` couldn't handle an `import` of OBO files from the new host. If I switch the extensions on the URIs to import it works without issue. That's a simple enough hacky fix. Looking at the HTTP headers, the only significant difference between the old host and the new one is that the new one uses at least one HTTP redirect while the other does not.

I'll add the work-around.

**Comment by mobiusklein** [comment]
It seems `robot` couldn't handle an `import` of an OBO, as it never tries an OBO parser on the import, trying every other thing under the sun.

**Comment by mobiusklein** [comment]
Fixed in #98

**Comment by edeutsch** [comment]
great, thank you for fixing!

**Pull request merged**
