### PR TITLE
Adds ProSight and TDPortal terms and mass array

### PR DESCRIPTION
**Pull request by mtrobey**
- adds ProSight and TDPortal terms, along with appropriate parent terms
- adds mass array term for applications such as CDMS that detect neutral masses

### CODE REVIEW

**Review by ypriverol — CHANGES_REQUESTED** [review]
Please check special characters in the terms.

**Comment by chambm** [comment]
`expected XrefList` (After the definition)

**Review by edeutsch — CHANGES_REQUESTED** [review]
3123 has already been proposed in PR #46 which is likely to be merged first, so please increment accession numbers.

also, data-version and date need to needs to be incremented at the top of the file. Note that PR #46 will likely be merged first so the data-version change should take that into account.

**Comment by mtrobey** [comment]
Thanks guys, I made those and it looks like the check passed. Let me know if there's anything else.

**Review by edeutsch — APPROVED** [review]
Looks good to me, thank you!

**Comment by mtrobey** [comment]
@ypriverol Hi Yasset, is there anything else you need from me? I think it's still waiting for you to okay the changes.

Thanks!

**Review by ypriverol — APPROVED** [review]

**Pull request merged**
