### PR TITLE
Add ETciD term

### PR DESCRIPTION
**Pull request by joseph-greer**
Added term for ETciD (combined ETD and CID)

### CODE REVIEW

**Comment by edeutsch** [comment]
I'm wondering if we already handle this case by specifying both the CID term and ETD term as a pair, rather than a single term?
@chambm thoughts?

**Comment by joseph-greer** [comment]
Just for background, I should have mentioned in the pr comment that I based this off the EThcD term.

**Comment by mobiusklein** [comment]
@joseph-greer Does the change from 59e34f1253dcaf5cab419eed27a30db7679ece97 meet your requirements?

**Comment by joseph-greer** [comment]
This looks good.

Thanks,

Joe

**Comment by edeutsch** [comment]
Closing in favor of replacement PR #84

**Pull request closed without merging**
