### PR TITLE
add mzQC format to the CV

### PR DESCRIPTION
**Pull request by mwalzer**
We (PSI-QC working group) would like to add mzQC as a file format term in the PSI-MS-CV

### CODE REVIEW

**Comment by mobiusklein** [comment]
Other than the CV version needing to be incremented, nothing here looks amiss.

Do you want to create an intermediate abstract term like "quality control file format" to allow things to refer to QC files of other types?

**Comment by mwalzer** [comment]
> Do you want to create an intermediate abstract term like "quality control file format" to allow things to refer to QC files of other types?
Yep, fair enough.

**Comment by mobiusklein** [comment]
Looks good to me now. Requesting a quick review from at least one other person before merging.

**Review by edeutsch — APPROVED** [review]
This looks good to me, thanks!

**Pull request merged**
