### PR TITLE
Protein contaminant ratio

### PR DESCRIPTION
**Pull request by cbielow**
Note: new version assumes that https://github.com/HUPO-PSI/psi-ms-CV/pull/245 is merged first.

### CODE REVIEW

**Review by bittremieux — APPROVED** [review]

**Comment by cbielow** [comment]
IMHO ready for merge from our side :)

**Review by edeutsch — COMMENTED** [review]
This looks okay to me, except maybe the "intensity" in the name. The name has "intensity" but the description only talks about "abundance".  These two concepts are related but not really equal. "ratio" and "fraction" are also variously used in ways that are unclear. "fraction of total protein" is clear. "ratio" only serves to confuse the issue, I think. 

I'm thinking the name would be better "contaminant protein abundance fraction".

**Comment by cbielow** [comment]
point well made.
Updated the name accordingly.

**Review by edeutsch — APPROVED** [review]
I still think it is better as "contaminant protein abundance fraction", i.e. with contaminant first, because we are talking about "contaminant protein"s and not really "protein contaminant"s.

But adequate as is.

**Comment by cbielow** [comment]
whops. Fixed the name. Thanks Eric.
Also updated the `data-version`, so it can be merged directly without relying on  #245 

Ready to merge.

**Pull request merged**
