### PR TITLE
Add Thermo Orbitrap Astral

### LINKED ISSUE #193: New term for Thermo Orbitrap Astral
### Describe the new term or terms you would like to add.

We would like to add a new term for the Thermo Orbitrap Astral mass spectrometer that was just released.
https://www.thermofisher.com/us/en/home/industrial/mass-spectrometry/liquid-chromatography-mass-spectrometry-lc-ms/lc-ms-systems/orbitrap-lc-ms/orbitrap-astral-mass-spectrometer.html

[Term]
id: MS:100xxxx
name: Orbitrap Astral
def: "Thermo Scientific Orbitrap Astral mass spectrometer contains three mass analyzers: a quadrupole analyzer, an Orbitrap analyzer, and the novel Astral analyzer." [PSI:PI]
is_a: MS:1000494 ! Thermo Scientific instrument model

### PR DESCRIPTION
**Pull request by mobiusklein**
Closes #193

### CODE REVIEW

**Review by edeutsch — APPROVED** [review]
Looks, great, thanks. I would drop the word "novel" since that modifier will become stale soon and it seems unnecessary.

**Review by edeutsch — APPROVED** [review]

**Comment by mobiusklein** [comment]
Do we also need a new mass analyzer term or will the Astral analyzer be described using the `time-of-flight` analyzer type?

**Comment by javizca** [comment]
The analyser is a new type (Astral, for asymmetric track lossless). It is a TOF like analyzer, but not exactly the same according too Thermo, so a new analyser would need to be created

**Comment by caetera** [comment]
Isn't Astral just a multi-reflection TOF, i.e. subtype of TOF?

Just want to "subscribe" for this PR to get the update when it is merged and update TRFP accordingly.

**Pull request merged**
