### PR TITLE
quantms added

### PR DESCRIPTION
**Pull request by ypriverol**
This PR add quantms to PSI MS as analysis software.

### CODE REVIEW

**Review by edeutsch — CHANGES_REQUESTED** [review]
I suggest a definition line like this:
```
def: "Cloud-based pipeline for quantitative proteomics that enables the reanalysis of public proteomics data." [PMID:38965444]
```

Also, I don't know if the changes to validate-owl.yaml are appropriate. @mobiusklein ?

**Comment by ypriverol** [comment]
@edeutsch the changes in the CI are correct. I just changed the previous URL from my private repo to the HUPO-PSI. I just change the definition.

**Review by mobiusklein — APPROVED** [review]

**Comment by ypriverol** [comment]
Related to issue #346

**Comment by ypriverol** [comment]
@mobiusklein @edeutsch can we merge this one?

**Comment by mobiusklein** [comment]
It just needs Eric to acknowledge his change request was satisfied.

**Review by edeutsch — APPROVED** [review]
approved, thanks.

**Pull request merged**
