### PR TITLE
Add first batch of mzqc readers/writers

### PR DESCRIPTION
**Pull request by cbielow**
@mwalzer 
@nilshoffmann
@bittremieux 
please have a look. Thanks! :)

I used the MS:4....... space, since its QC software.

Was also wondering if we should have a new term like
```
[Term]
id: MS:?????
name: quality control software
def: "Quality Control software." [PSI:MS]
is_a: MS:1000531 ! software
```
which we can derive from.

### CODE REVIEW

**Comment by edeutsch** [comment]
I'm thinking software package names ought to go in the MS:1000 series. What do you think?

**Comment by cbielow** [comment]
Fine with me as well.

**Comment by nilshoffmann** [comment]
@cbielow Should we rather use
`is_a: MS:1001457 ! data processing software` for the new root term "Quality Control software"?

**Comment by cbielow** [comment]
ok, done.

@bittremieux  @mwalzer Is this good to go?

**Review by edeutsch — APPROVED** [review]

**Comment by edeutsch** [comment]
We looked at the latest diff at the PSI-MS and were all happy with this as is. Waiting for review by @bittremieux and @mwalzer before merge.

**Review by mobiusklein — APPROVED** [review]

**Review by bittremieux — APPROVED** [review]

**Comment by cbielow** [comment]
We've briefly touched upon this PR in the mzQC meeting yesterday, so we should be good to merge.

**Pull request merged**
