### PR TITLE
Add ion mobility attribute as parent for CCS

### PR DESCRIPTION
**Pull request by chambm**
As discussed on PSI call, we want to allow CCS to be encoded in mzML wherever individual ion mobility values are currently allowed.

### CODE REVIEW

**Review by edeutsch — APPROVED** [review]

**Comment by edeutsch** [comment]
This looks good, thanks. It was mentioned at the call today that several vendor APIs allow for computing the CCS when reading vendor datafiles, so this could be easily encoded in the mzMLs.

**Review by mobiusklein — APPROVED** [review]
Looks good to me. There's a degree of approximation error that we don't really understand but there's nothing to be done about it. Because CCS requires knowledge of charge state, it doesn't yet seem feasible to encode on a peak level.

**Comment by edeutsch** [comment]
but this is for precursors I think, right? where the charge state is ostensibly known?

**Comment by chambm** [comment]
Yes, it only makes sense when charge state is relevant. So unlike drift time et al., it actually doesn't make sense in `<scan>`, only in `<selectedIon>`. However, it is feasible to have an array of CCS values just like we can have an array of charge states. Unknown values could be stored as 0. I think we can leave that for another PR though.

**Pull request merged**
