### PR TITLE
add MsQuality Term

### PR DESCRIPTION
**Pull request by tnaake**
Hi,

I would like to add a term related to the [`MsQuality`](https://bioconductor.org/packages/release/bioc/html/MsQuality.html) software that uses mzQC terms. In a second step, after adding the term for `MsQuality`, we would like to integrate our tool with the `rmzqc` package. 

Currently, the manuscript is available on BioRXiv (see the DOI). Upon acceptance, we would also like to update the DOI to the new DOI (I think in that case I will create another PR). 

EDIT: in the second commit, I have added several QC metrics that were previously present in [PSI:QC] but I could not find them in the current [PSI:MS]. Could I please ask you to include them or explain why they weren't transfered to [PSI:MS]? The MsQuality package uses these terms and it would be great to still use them in the next versions.

Many thanks and please let me know, if I need to do anything else.

Best,
Thomas

### CODE REVIEW

**Review by edeutsch — CHANGES_REQUESTED** [review]
By convention, term names should not begin with capital letter unless proper name or acronym

**Comment by tnaake** [comment]
Thanks for the comment! 

I have changed the `name` to lower-case letters. `The `MsQuality` remains unchanged since it refers to a piece of software.

**Comment by mobiusklein** [comment]
@tnaake I think something went awry when you added the commit to your fork, it's not associated with any branch in your repository.

I had added a commit to update the version number to your fork's `master` branch. You _should_ have been notified that your local copy was out of sync when you pushed again, but it seems not?

**Comment by tnaake** [comment]
Hi @mobiusklein ,
thanks for the comment. I am not sure what went wrong here. Do you think it's best to close this PR and open a new one? Or is there a way to continue with the integration on this PR.

**Comment by mobiusklein** [comment]
I don't know what state your branch is in on your machine, but I was able salvage them on a new branch and handle merge conflicts. I'll open a new PR for your changes shortly.

**Comment by edeutsch** [comment]
closing since this is replaced by #206

**Pull request closed without merging**
