### PR TITLE
Update Scout score (MS:1003408)

### PR DESCRIPTION
**Pull request by colin-combe**
give it an is_a relationship to MS:1001143 'PSM-level search engine specific statistic'

### CODE REVIEW

**Review by ypriverol — CHANGES_REQUESTED** [review]
@colin-combe you have to update the version of the file ono and also the last person that modify it. If not the PR will fail.

**Comment by colin-combe** [comment]
@ypriverol - where does this info go?

**Comment by ypriverol** [comment]
Top of the file: 
```
format-version: 1.2
data-version: 4.1.155
date: 03:06:2024 13:22
saved-by: Eric Deutsch
```

**Comment by colin-combe** [comment]
OK, thanks. Thought it was that, was just checking. Should be updated now.

**Review by edeutsch — APPROVED** [review]

**Review by ypriverol — APPROVED** [review]

**Pull request merged**
