### PR TITLE
DIA-NN added

### PR DESCRIPTION
**Pull request by ypriverol**

### CODE REVIEW

**Review by edeutsch — CHANGES_REQUESTED** [review]
- The 4000000 series is for mzQC, the 1000000 series should be used for general terms like this
- Also, no changes to the OWL file are needed because the OWL is auto-genererated from the OBO
- Would you make the attribution instead of [PSI-MI] make it [PMID:31768060, https://github.com/vdemichev/DiaNN] instead? or another PMID or URL if more appropriate than my suggestion?

thanks!

**Comment by mobiusklein** [comment]
The OWL changes are happening automatically because even on forks, commits to `master` run the automatic OWL file generation GitHub Action. They probably also try to tag and publish releases, but I don't know if it works.

**Comment by edeutsch** [comment]
oh I see, if it's a PR from a local branch in this repo, that doesn't happen, but if it's a PR from a fork, then that will happen, got it. @ypriverol, scratch my comment about the OWL then. Not relevant. just my ignorance of GitHub.

**Comment by ypriverol** [comment]
@edeutsch done!!

**Review by edeutsch — APPROVED** [review]
looks great to me, thanks!

**Review by mobiusklein — APPROVED** [review]
Looks good to me.

**Pull request merged**
