### PR TITLE
timsTOF fleX instrument added 

### PR DESCRIPTION
**Pull request by ypriverol**

### CODE REVIEW

**Review by edeutsch — CHANGES_REQUESTED** [review]
I think a better parent would be:
is_a: MS:1001534 ! Bruker Daltonics flex series

What do you think?

**Review by edeutsch — CHANGES_REQUESTED** [review]
also, each change should increment the data-version number

**Comment by chambm** [comment]
Probably need a new parent for timsTOF instruments. Because I think the only thing it shares in common with the flex series is the MALDI source (which is probably very different, MALDI-2 apparently).

**Comment by edeutsch** [comment]
Yes, that sounds sensible. So add a new term:

Bruker Daltonics timsTOF series

and this proposed term and also previous term:
id: MS:1003005
name: timsTOF Pro

under this new parent, too?

**Comment by ypriverol** [comment]
@edeutsch @chambm I did the requested changes.

**Review by chambm — APPROVED** [review]

**Review by edeutsch — APPROVED** [review]
Looks great, thanks! Ready to merge!

**Pull request merged**
