### PR TITLE
Alternative EThcD with new parent term

### PR DESCRIPTION
**Pull request by edeutsch**

### CODE REVIEW

**Review by mobiusklein — APPROVED** [review]
As discussed, the supplemental energy term resolves my concerns about ambiguity

**Review by ypriverol — APPROVED** [review]
@edeutsch I see that we have changed the names of all therms to lowercase for the first letter. Is that a consensus. ? 

@mobiusklein @edeutsch the check for obo  is failing.

**Review by mobiusklein — APPROVED** [review]
Updated header

**Comment by edeutsch** [comment]
> @edeutsch I see that we have changed the names of all therms to lowercase for the first letter. Is that a consensus. ?

I believe that this is our custom, and thus I made the change to conform to the custom.
I don't think this term is currently used by ProteoWizard so the likelihood of breaking existing code seems low. but possible.
I think it's a good idea. But don't feel strongly.
If anyone objects, please speak up!

**Comment by chambm** [comment]
Yes, pwiz is not using these terms. I missed the conversation about why we need combined terms to reduce ambiguity vs. the old approach of having both the CID/HCD term and the ETD term. Is the new way supposed to be in addition to or instead of the old way?

**Comment by edeutsch** [comment]
My suggestion is for pwiz not to do anything differently and the recommendation for mzML is to keep doing what we've always been doing. But for other applications that want a single term, it seems useful to have these two combined modes. 

Note that there is a term "supplemental collision energy" to capture the collision energy of the supplemental activation for these combined modes.

**Comment by chambm** [comment]
Seems pretty confusing to handle it different between different formats, but I guess that's not new. :/

**Review by chambm — APPROVED** [review]

**Pull request merged**
