### PR TITLE
Add 3 new Waters instruments

### PR DESCRIPTION
**Pull request by edeutsch**

### CODE REVIEW

**Review by ypriverol — APPROVED** [review]

**Review by chambm — CHANGES_REQUESTED** [review]
Those instrument names look like the start of SQL queries :joy: - but if that's how Waters styles them, that's correct. Needs version bump.

**Review by mobiusklein — APPROVED** [review]
After the header fix, this looks fine to me. I'm guessing these instruments have the same source/mass analyzer/detector terms as previous instruments?

**Review by chambm — APPROVED** [review]

**Comment by edeutsch** [comment]
> After the header fix, this looks fine to me. I'm guessing these instruments have the same source/mass analyzer/detector terms as previous instruments?

I don't really know. I now realize that I should have tagged @HansVissers to review this. Will do now.

**Comment by edeutsch** [comment]
@HansVissers are you happy with these definitions:
https://github.com/HUPO-PSI/psi-ms-CV/pull/85/files
?

Or would you like to amend the definitions?

**Comment by HansVissers** [comment]
> @HansVissers are you happy with these definitions:
> https://github.com/HUPO-PSI/psi-ms-CV/pull/85/files
> ?
> 
> Or would you like to amend the definitions?

@edeutsch, These look fine.

**Comment by edeutsch** [comment]
okay, thanks.
@mobiusklein I think we are ready to merge #79, #84, and #85, would you try to merge then in? I don't know that I could gracefully deal with the conflicts.

**Pull request merged**
