### PR TITLE
add value type for FAIMS compensation voltage

### PR DESCRIPTION
**Pull request by timosachsenberg**

### CODE REVIEW

**Review by edeutsch — APPROVED** [review]
Looks like a good fix. I wonder why this wasn't already there. Do you suppose it should have units as well? Or is the units always just volts and thus unnecessary?

**Comment by timosachsenberg** [comment]
I think it is volts UO:0000218 and we could add it as well

**Review by edeutsch — CHANGES_REQUESTED** [review]
Looks great. Would you also bump the version number and date at the top of the file?

**Review by edeutsch — APPROVED** [review]
Great, cleared to merge IMO
@ypriverol or anyone else have concerns?

**Review by ypriverol — APPROVED** [review]

**Pull request merged**
